-- Create the articles table
create table public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  status text check (status in ('draft', 'published')) default 'draft',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.articles enable row level security;

-- Create a policy that allows anyone to read articles (for now, or maybe just authenticated users?)
-- For a CMS, usually only authenticated users can create/update.
-- For simplicity in this demo, we will allow public insert if no auth is set up yet, 
-- BUT since we have a login page, we should probably assume some auth.
-- However, we haven't implemented real Supabase Auth in the login page yet (just simulation).
-- So to make this "Save" work without blocking, I'll create a policy allowing public access for demo purposes.
-- PROD WARNING: Change this to authenticated only for real use.

create policy "Enable access to all users" on public.articles for all using (true) with check (true);
